### ISSUE TITLE
Rename BlindSign

### ISSUE THREAD

**Issue by chris-wood** [chris-wood/draft-wood-cfrg-eddsa-blinding#5]
This isn't a blind signature. It's rather "sign using a blinded private key." There's probably a better way to describe this operation.

**Comment by chris-wood** [comment]
@jedisct1, any thoughts?

**Comment by jedisct1** [comment]
Indeed, calling it a blind signature would be confusing.

`BlindKeySign` maybe?

**Comment by chris-wood** [comment]
Yeah, that's better! Do you want to send a PR? =)
